version: '3'
services:
    mcl:
        restart: always
        container_name: mcl
        build: ./mcl
        volumes:
            - ./mcl/logs:/mcl/logs
        command: [ 'java', '-jar', './mcl.jar' ]
        expose:
            - 8765
        networks:
            - mirai_net
    connector:
        restart: always
        container_name: connector
        build: ./custom/connector
        command: [ 'node', './main.js' ]
        networks:
            - mirai_net
        depends_on:
            - mcl
    connector_npm_repo:
        restart: always
        container_name: connector_npm_repo
        image: sonatype/nexus3:latest
        ports:
            - "8701:8081"

networks:
    mirai_net:
        driver: bridge
