version: '3'
services:
    mcl:
        restart: always
        container_name: mcl
        build: ./mcl
        volumes:
            - ./mcl/logs:/mcl/logs
        command: [ 'java', '-jar', './mcl.jar' ]
        expose:
            - 8765
        networks:
            - mirai_net
    connector:
        restart: always
        container_name: connector
        build: ./custom/connector
        command: [ 'bash', './startApp.sh' ]
        networks:
            - mirai_net
        expose:
            - 8764
        volumes:
            - ./custom/connector/logs:/root/.npm/_logs
            - ./custom/connector:/origin
            - ./custom/connector/files:/app/files
        depends_on:
            - mcl
    connector_npm_repo:
        restart: always
        container_name: connector_npm_repo
        image: verdaccio/verdaccio:latest
        environment:
            - VERDACCIO_PORT=4873
        ports:
            - "8701:4873"
        volumes:
            - "./custom/connector_npm_repo/storage:/verdaccio/storage"
            - "./custom/connector_npm_repo/conf:/verdaccio/conf"
            - "./custom/connector_npm_repo/plugins:/verdaccio/plugins"

networks:
    mirai_net:
        driver: bridge
