storage: /verdaccio/storage/
plugins: /verdaccio/plugins/
web:
    enable: true
    title: 私有 NPM 仓库
    gravatar: true
    login: true
    pkgManagers:
        - npm
        - yarn
        - pnpm
    html_cache: true
    showFooter: false
auth:
    htpasswd:
        file: ./htpasswd
        algorithm: md5 # 这里选择 md5 作为加密算法
i18n:
    web: zh-CN
security:
    api:
        jwt:
            sign:
                expiresIn: 60d
                notBefore: 1
    web:
        sign:
            expiresIn: 7d
uplinks:
    npmjs:
        url: https://registry.npmjs.org/
        cache: false
    yarn:
        url: https://registry.yarnpkg.com/
        timeout: 10s
        cache: false
    taobao:
        url: https://npmmirror.com/
        timeout: 10s
        cache: false

packages:
    "@chlamydbot/*":
        access: $all # "$all", "$anonymous", "$authenticated"
        publish: $authenticated
        unpublish: $authenticated
    "@*/*":
        access: $all
        publish: $authenticated
        unpublish: $authenticated
        proxy: taobao npmjs yarn
    "**":
        access: $all
        publish: $authenticated
        unpublish: $authenticated
        proxy: taobao npmjs yarn
middlewares:
    audit:
        enabled: true
listen: 0.0.0.0:4873
log: { type: stdout, format: pretty, level: http }
