FROM openjdk:17

RUN mkdir /mcl
WORKDIR /mcl
ADD ./mcl.jar /mcl/mcl.jar
ADD ./config.json /mcl/config.json
ADD ./bots /mcl/bots
ADD ./config /mcl/config
ADD ./data /mcl/data
ADD ./libs /mcl/libs
ADD ./plugin-libraries /mcl/plugin-libraries
ADD ./plugin-shared-libraries /mcl/plugin-shared-libraries
ADD ./plugins /mcl/plugins