adapters:
    - http
    - ws
debug: false
enableVerify: true
verifyKey: CHLAMYDOMONOS
singleMode: false
cacheSize: 4096
persistenceFactory: "built-in"
adapterSettings:
    http:
        host: 0.0.0.0
        port: 8765
        cors: ['*']
        unreadQueueMaxSize: 0

    ws:
        host: 0.0.0.0
        port: 8765
        reservedSyncId: -1
